### PR TITLE
Sorting and filtering products

### PR DESCRIPTION
**Pull request by RakshaPawar108**
**Changes made since last PR**

- Added filter-context and reducer
- Added sorting by price
- Added filtering by categories
- Added filtering with price range
- Added discount calculation and rating to database and ui
- Added miscellaneous filters like newest, bestsellers and availability in stock
- Added filtering by rating

Preview link given below

### CODE REVIEW

**Review by Kevin-Solomon — APPROVED** [review]
Could change ```state``` to ```filterState``` but this is just a nit pick.

**Review by Kevin-Solomon — CHANGES_REQUESTED** [review]
There is a small bug in the sort function.
The sort feature is not working as expected.
image

Fix this by converting the ```Number(prod.price)``` in the sort util function.

**Comment by RakshaPawar108** [comment]
> There is a small bug in the sort function. The sort feature is not working as expected. image
> 
> Fix this by converting the `Number(prod.price)` in the sort util function.

Thanks for pointing this bug out Kevin. Fixed it now

**Review by Kevin-Solomon — APPROVED** [review]

**Review by Abhijeet43 — APPROVED** [review]
The Filters are working fine!!... Code structure is also good

**Pull request merged**
